package com.example.cerberus.statemachine

/**
 * Represents the different events that can trigger state transitions
 * in the app lock management system. These events are generated by
 * the EventProcessor based on accessibility events and user interactions.
 */
enum class AppEvent {
    /**
     * A locked app has been launched and brought to foreground
     */
    APP_LAUNCHED,

    /**
     * Authentication prompt has been displayed to the user
     */
    AUTH_PROMPT_SHOWN,

    /**
     * User has successfully completed authentication
     */
    AUTH_SUCCESS,

    /**
     * User has failed authentication attempt
     */
    AUTH_FAILED,

    /**
     * User performed a gesture indicating they're moving app to background
     * (e.g., home button, recent apps, navigation gesture)
     */
    BACKGROUND_GESTURE,

    /**
     * User has returned to a previously backgrounded app
     */
    APP_RETURNED,

    /**
     * Idle timeout has expired for the app session
     */
    TIMEOUT_EXPIRED,

    /**
     * App has been explicitly closed or killed
     */
    APP_CLOSED
}